#!/bin/bash

# ble.sh () installed from nix
if (command -v blesh-share &>/dev/null); then
	source "$(blesh-share)"/ble.sh --attach=none # does not work currently
	# ...
	[[ ${BLE_VERSION-} ]] && ble-attach
	# source "$(blesh-share)"/ble.sh
fi
