#!/bin/bash

if (asdf which direnv &>/dev/null); then
	# Hook direnv into your shell.
	eval "$(asdf exec direnv hook bash)"

	# A shortcut for asdf managed direnv.
	direnv() { asdf exec direnv "$@"; }

	return

elif (command -v direnv &>/dev/null); then
	# Hook direnv into your shell.
	eval "$(direnv hook bash)"

fi
