#!/bin/bash

# GNU Screen stuff
if (command -v tmux &>/dev/null); then
  if [ "$(pgrep -u "$UID" "tmux" | wc -l)" -gt 0 ]; then
    if [[ $TERM != screen* ]]; then
      nb_sessions=$(tmux list-session | wc -l)
      nb_sessions_attached=$(tmux list-session | grep -c "attached")
      nb_sessions_detached=$(tmux list-session | grep -c -v "attached")

      echo_info "Found ${nb_sessions} tmux session(s)"

      echo " * ${nb_sessions_attached} attached"
      tmux list-sessions | grep "attached" | sed -e 's/^/     - /'

      echo " * ${nb_sessions_detached} detached"
      tmux list-sessions | grep -v "attached" | sed -e 's/^/     - /'

    fi
  fi
fi
