#!/bin/bash

URXVT_FONT_NAME="Terminus"
URXVT_FONT_SIZE=8
URXVT_FONT_INCREMENT=1

urxvt_set_font "${URXVT_FONT_NAME}:size=${URXVT_FONT_SIZE}"

# Quick functions

zp() {
	URXVT_FONT_SIZE=$(echo "$URXVT_FONT_SIZE+$URXVT_FONT_INCREMENT" | bc )
	urxvt_set_font "${URXVT_FONT_NAME}:size=${URXVT_FONT_SIZE}"
}

zm() {
	URXVT_FONT_SIZE=$(echo "$URXVT_FONT_SIZE-$URXVT_FONT_INCREMENT" | bc )
	urxvt_set_font "${URXVT_FONT_NAME}:size=${URXVT_FONT_SIZE}"
}
