#!/bin/bash

# Powerline
SCRIPT=/usr/lib64/python3.2/site-packages/powerline/bindings/bash/powerline.sh
if [ -f $SCRIPT ]
then
	if [ -n "$SSH_CONNECTION" ]
	then
			#urxvt_set_font "Terminus for Powerline-12"
			export URXVT_FONT_NAME="DejaVu Sans Mono"
			urxvt_set_font "DejaVu Sans Mono for Powerline-10"
			source $SCRIPT
	fi
fi
