#!/bin/bash

# https://github.com/riywo/anyenv

# git clone https://github.com/riywo/anyenv $HOME/.anyenv

if [ -d "$HOME/.anyenv/bin" ]
then
  export PATH="$HOME/.anyenv/bin:$PATH"
  eval "$(anyenv init -)"
fi
