#!/bin/bash

# Defined prefered applications

# EDITOR
if (command -v nvim &>/dev/null); then
	export EDITOR=nvim
fi

# PAGER
export PAGER=less

# MANPAGER
if (command -v nvim &>/dev/null); then
	export MANPAGER='nvim +Man!'
elif (command -v bat &>/dev/null); then
	export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# TERMINAL
export TERMINAL=kitty

# BROWSER
export BROWSER=firefox
