#!/bin/bash

# Customize history format
export HISTSIZE=5000
export HISTFILESIZE=20000
export HISTTIMEFORMAT="[%d/%m/%Y %H:%M:%S] "
export HISTCONTROL="ignoreboth"
export HISTIGNORE="history*:exit:reboot:^rm:[bf]g:ls:ll:help:man:mutt:pass"
