#!/bin/bash

# Customize history format
export HISTSIZE=5000
export HISTFILESIZE=20000
export HISTTIMEFORMAT="[%d/%m/%Y %H:%M:%S] "
export HISTCONTROL="ignoreboth"
export HISTIGNORE="[bf]g:exit:history*:*rm*-rf*:*rm*-f*:reboot:ls:ll:man:mutt"
