#!/bin/bash

# Customize PATH
if [ -d $HOME/.bin ] ; then export PATH=$PATH:$HOME/.bin ; fi
if [ -d $HOME/.local/bin ] ; then export PATH=$PATH:$HOME/.local/bin ; fi

if [ -d $HOME/bin ] ; then export PATH=$PATH:$HOME/bin ; fi
if [ -d $HOME/scripts ] ; then export PATH=$PATH:$HOME/scripts ; fi
