#!/bin/bash

#SSH
if [ -e ~/.ssh/config ]; then
	complete -W "$(cat ~/.ssh/config | egrep  -i "^\s*host\s+[a-zA-Z]" | sed -e "s/^host\s*//i")" ssh
fi

if [ -e ~/.ssh/known_hosts ]; then
	complete -W "$(cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | grep -v "\[")" ssh
fi
