#!/bin/bash

# Defined prefered applications

# EDITOR
if (command -v nvim &>/dev/null); then
	export EDITOR=nvim
fi

# PAGER
if (command -v less &>/dev/null); then
	export PAGER=less
fi

# MANPAGER
if (command -v nvim &>/dev/null); then
	export MANPAGER='nvim +Man!'
elif (command -v bat &>/dev/null); then
	export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# TERMINAL
if (command -v kitty &>/dev/null); then
	export TERMINAL=kitty
fi

# BROWSER
if (command -v firefox &>/dev/null); then
	export BROWSER=firefox
fi
