#!/bin/bash

# Git
if [ -x /usr/bin/git ]
then
  alias gs='git status'
  alias ga='git add'
  alias gc='git commit'
  alias gca='git commit -a'
  alias gp='git push'
  alias gu='git pull'
  alias gd='git diff'
  alias gdc='git diff --cached'
  alias gb='git branch'
  alias gco='git checkout'
  alias gw='git whatchanged'
  alias gl='git log --graph'

  alias glog='git log'
  alias gshow='git show'
  alias glast='git last'
  alias gstatus='git status'
  alias gdiff='git diff'
  alias gcommit='git commit'
  alias gcommitall='git commit --all'
  alias greset='git reset'
  alias gpull='git pull'
  alias gpush='git push'
fi
