#!/bin/bash

# Vim Editor
if (command -v lvim &> /dev/null)
then
  alias vim=lvim
elif (command -v nvim &> /dev/null)
then
  alias vim=nvim
fi
# if [ -x /usr/bin/vim ]
# then
#   alias vi='vim -p'
#   alias view='vim -R'
#   alias vless='vim -u /usr/share/vim/vim*/macros/less.vim'
# fi
